services:

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '4000:4000'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5678:5678"
    environment:
      - VITE_API_URL=http://localhost:4000/api
    depends_on:
      - server